apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: swift-chat

resources:
  - namespace.yaml
  - configmap.yaml
  - persistent-volume.yaml
  - gatesvr-deployment.yaml
  - zonesvr-deployment.yaml
  - authsvr-deployment.yaml
  - onlinesvr-deployment.yaml
  - friendsvr-deployment.yaml
  - chatsvr-deployment.yaml
  - filesvr-deployment.yaml

commonLabels:
  app.kubernetes.io/name: swift-chat
  app.kubernetes.io/version: "0.1.0"
